# cSpell: disable
version: '3.8'

services:
  nieve_auto:
    image: ericklinares/gee-nieve-sequia-auto:3.0.0
    deploy:
      replicas: 1 
      resources: 
        limits:
          #cpus: '1'
          memory: '2G'
    environment:
      - SNOW_SERVICE_USER=odes-nieve@ee-proyectosequiateleamb.iam.gserviceaccount.com
      - SNOW_SERVICE_CREDENTIALS_FILE=/run/secrets/credentials      
      - SNOW_EXPORT_TO=toAssetAndDrive
      - SNOW_ASSETS_PATH=projects/ee-proyectosequiateleamb/assets/nieve/raster_sci_cci
      - SNOW_DRIVE_PATH=raster_sci_cci
      - SNOW_REGIONS_ASSET_PATH=users/proyectosequiateleamb/Regiones/DPA_regiones_nacional
      - SNOW_MONTHS_LIST=2023-10-01, 2023-09-01
     # - SNOW_ENABLE_EMAIL='True'
      - SNOW_SMTP_SERVER=mail.chompipes.com
      - SNOW_SMTP_PORT=587
      - SNOW_SMTP_USERNAME=erick
      - SNOW_SMTP_PASSWORD_FILE=/run/secrets/smtp_password
      - SNOW_FROM_ADDRESS=erick@chompipes.com
      - SNOW_TO_ADDRESS="erick@chompipes.com;erick.linares@gmail.com"
      - SNOW_SCHEDULER=True
      - SNOW_CRON='0 0 * * *'
      
    secrets:
      - credentials
      - smtp_password

    networks:
      - snow_auto
    
secrets:
  credentials:
    file: 'credentials/ee-proyectosequiateleamb-22dbf24d5c96.json'
  smtp_password:
    file: 'credentials/smtp_password.txt'

networks:
  snow_auto:
