version: '3.8'

services:
  nieve_auto:
    image: ericklinares/gee-nieve-sequia-auto:2.0.1
    deploy:
      replicas: 1 
      resources: 
        limits:
          cpus: '1'
          memory: '2G'
    environment:
      - SERVICE_USER=user@dummy_project.iam.gserviceaccount.com
      - SERVICE_CREDENTIALS_FILE=credentials
      - REGIONS_ASSET_PATH = 'users/proyectosequiateleamb/Regiones/DPA_regiones_nacional'
      - EXPORT_TO='toAssetAndDrive'
      - ASSETS_PATH='projects/ee-proyectosequiateleamb/assets/nieve/raster_sci_cci'
      - DRIVE_PATH='raster_sci_cci'
    
    secrets:
      - credentials
    
secrets:
  credentials:
    file: credentials/dummy_credentials.json
    
